"""Isolated browser evidence for actual execution and history, never user state."""
import json

from test_acceptance_browser import browser, engine_url, isolated_url, pytestmark
from test_acceptance_browser_mapping import HELPERS, count, counted_source, durable_runs


def test_browser_settings_export_downloads_portable_template(isolated_url):
    browser(isolated_url,r"""
 const {id,...template}=(await request('/api/workflow-templates'))[0];const w=await seed(template);await open(w);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByText('Advanced settings',{exact:true}).click();assert.deepEqual(await page.locator(':invalid').evaluateAll(xs=>xs.map(x=>({tag:x.tagName,type:x.type,value:x.value,message:x.validationMessage}))),[]);const exported=page.waitForResponse(r=>r.url().endsWith('/export'));const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export portable template',exact:true}).click();const response=await exported;assert.equal(response.status(),200,await response.text());assert.ok((await download).suggestedFilename().endsWith('.json'));
 """)


def test_browser_published_run_retains_unsaved_marker_and_executes_v1(engine_url,tmp_path):
    marker=tmp_path/'published-counter.txt'
    sources=[counted_source(marker,"{'summary':{'count':3,'total':'30.75'}}"),counted_source(marker,"{'summary':{'count':9,'total':'30.75'}}")]
    browser(engine_url,HELPERS+'const sources='+json.dumps(sources)+';'+r"""
 const {id,...template}=(await request('/api/workflow-templates'))[0];template.nodes.find(n=>n.id==='summary').source=sources[0];const w=await seed(template);const v1=await request('/api/workflows/'+w.id+'/publish','POST',{});await open(w);await sourceCode('summary',sources[1]);const pending=page.waitForResponse(r=>r.url().endsWith('/run'));await page.getByRole('button',{name:'Run published',exact:true}).click();const response=await pending;assert.equal(response.status(),202);const accepted=await response.json();assert.equal(accepted.status,'queued');const run=await waitRun(accepted);assert.equal(run.status,'succeeded',run.error);assert.equal(run.version_id,v1.version_id);assert.deepEqual(run.nodes.summary.output.data.summary,{count:3,total:'30.75'});assert.equal(await page.getByLabel('Source code',{exact:true}).inputValue(),sources[1]);assert.ok((await page.locator('.wf-save-state').textContent()).includes('Unsaved'));assert.equal((await request('/api/workflows/'+w.id)).nodes.find(n=>n.id==='summary').source,sources[0]);assert.equal((await request('/api/workflow-runs')).length,1);
 """)
    assert count(marker)==['invoked']
    assert next(n for n in durable_runs(tmp_path)[0]['snapshot']['nodes'] if n['id']=='summary')['source']==sources[0]


def test_browser_draft_test_freezes_marker4_before_later_edit(engine_url,tmp_path):
    marker=tmp_path/'draft-counter.txt';gate=tmp_path/'release-test.txt'
    frozen=counted_source(marker,"{'summary':{'count':4,'total':'30.75'}}").replace("    return",f"    import time\n    while not Path({str(gate)!r}).exists(): time.sleep(.05)\n    return")
    sources=[counted_source(marker,"{'summary':{'count':3,'total':'30.75'}}"),frozen,counted_source(marker,"{'summary':{'count':9,'total':'30.75'}}")]
    browser(engine_url,HELPERS+'const sources='+json.dumps(sources)+';const gate='+json.dumps(str(gate))+';'+r"""
 const {id,...template}=(await request('/api/workflow-templates'))[0];template.nodes.find(n=>n.id==='summary').source=sources[0];const w=await seed(template);const v1=await request('/api/workflows/'+w.id+'/publish','POST',{});await open(w);await sourceCode('summary',sources[1]);assert.ok((await page.locator('.wf-inspector').textContent()).includes('Tests execute real code and may have side effects'));const pending=page.waitForResponse(r=>r.url().endsWith('/run'));await page.getByRole('button',{name:'Test workflow',exact:true}).click();const response=await pending;assert.equal(response.status(),202);const accepted=await response.json();assert.equal(accepted.status,'queued');assert.equal(accepted.test,true);await page.waitForFunction(id=>document.querySelector('.wf-run-drawer')?.textContent.includes(id),accepted.id);await sourceCode('summary',sources[2]);(await import('node:fs')).writeFileSync(gate,'release');const run=await waitRun(accepted);assert.equal(run.status,'succeeded',run.error);assert.deepEqual(run.nodes.summary.output.data.summary,{count:4,total:'30.75'});assert.equal((await request('/api/workflows/'+w.id)).published_version_id,v1.version_id);assert.equal(await page.getByLabel('Source code',{exact:true}).inputValue(),sources[2]);assert.deepEqual(await request('/api/workflow-notifications'),[]);await page.getByRole('button',{name:'Runs',exact:true}).click();await page.getByText('Draft test',{exact:true}).waitFor();assert.ok((await page.locator('.table').textContent()).includes(accepted.id.slice(0,12)));
 """)
    assert count(marker)==['invoked']
    run=durable_runs(tmp_path)[0]
    assert run['test'] and next(n for n in run['snapshot']['nodes'] if n['id']=='summary')['source']==frozen


def test_browser_missing_engine_fails_actionably_without_local_fallback(request,monkeypatch,tmp_path):
    monkeypatch.setenv('SLEEP_IN_TEST_N8N_COMMAND',json.dumps([str(tmp_path/'genuinely-missing-n8n')]))
    url=request.getfixturevalue('engine_url');marker=tmp_path/'forbidden-fallback.txt'
    browser(url,HELPERS+'const source='+json.dumps(counted_source(marker))+';'+r"""
 const w=await seed({nodes:[node('p',{source})],edges:[]});await open(w);const run=await testRun(w);assert.equal(run.status,'failed');assert.ok(/n8n|executable|No such file|not found/i.test(run.error));assert.equal(run.nodes.p.attempts.length,0);await page.goto(origin+'/workflow-runs/'+run.id);await page.locator('.wf-run-summary').getByText('Failed',{exact:true}).waitFor();assert.ok((await page.locator('.wf-error').textContent()).length>10);await page.reload();await page.locator('.wf-run-summary').getByText('Failed',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).count(),0);
 """)
    assert count(marker)==[]


def test_browser_logs_attempts_download_and_reload_stay_with_exact_run(engine_url,tmp_path):
    marker=tmp_path/'logs-python.txt';js_marker=tmp_path/'logs-js.txt'
    browser(engine_url,HELPERS+'const markers='+json.dumps([str(marker),str(js_marker)])+';'+r"""
 const bad=await seed({nodes:[node('bad',{source:'def main(inputs): raise RuntimeError("prior-failure-only")'})],edges:[]});await open(bad);const failed=await testRun(bad);assert.equal(failed.status,'failed');const {id,...template}=(await request('/api/workflow-templates'))[0];const canary='<img src=x onerror="window.executionXss=true"><script>window.executionXss=true</script>';template.name=canary;const py=template.nodes.find(n=>n.id==='summary');py.source=py.source.replace('    rows =','    import sys\n    from pathlib import Path\n    Path('+JSON.stringify(markers[0])+').open("a").write("invoked\\n")\n    print("current-python-out")\n    print("current-python-err", file=sys.stderr)\n    rows =');template.nodes.find(n=>n.id==='report').source+='\nrequire("fs").appendFileSync('+JSON.stringify(markers[1])+',"invoked\\n"); console.log("current-js-out"); console.error("current-js-err");';py.source+='\nprint('+JSON.stringify(canary)+')\nimport sys\nprint('+JSON.stringify(canary)+',file=sys.stderr)\n';const w=await seed(template);await page.goto(origin+'/workflows');const listCard=page.locator('.wf-list-card').filter({hasText:canary});assert.ok((await listCard.textContent()).includes(canary));assert.equal(await listCard.locator('img,script').count(),0);assert.equal(await page.evaluate(()=>window.executionXss),undefined);await open(w);const pending=page.waitForResponse(r=>r.url().endsWith('/run'));await page.getByRole('button',{name:'Test workflow',exact:true}).click();const accepted=await(await pending).json();await page.goto(origin+'/workflow-runs/'+accepted.id);await page.reload();const run=await waitRun(accepted);assert.equal(run.status,'succeeded',run.error);await page.goto(origin+'/workflow-runs');await page.getByRole('button',{name:run.id.slice(0,12),exact:true}).click();await page.locator('.wf-run-summary').getByText('Succeeded',{exact:true}).waitFor();
 for(const [id,value] of Object.entries(run.nodes)){const card=page.locator('.wf-node-detail').filter({has:page.locator('summary strong').filter({hasText:value.name})});await card.locator('summary').first().click();assert.ok((await card.textContent()).includes('Inputs'));assert.ok((await card.textContent()).includes('Outputs'));await card.getByText('Attempts',{exact:true}).click();assert.equal(value.attempts.length,1);if(id==='summary'){assert.ok((await card.textContent()).includes('current-python-out'));assert.ok((await card.textContent()).includes('current-python-err'));}if(id==='report'){assert.ok((await card.textContent()).includes('current-js-out'));assert.ok((await card.textContent()).includes('current-js-err'));}}
 const content=await page.locator('body').textContent();for(const text of ['current-python-out','current-python-err','current-js-out','current-js-err'])assert.ok(content.includes(text));assert.equal(content.includes('prior-failure-only'),false);assert.ok(run.nodes.summary.stdout.includes(canary));assert.ok(run.nodes.summary.stderr.includes(canary));assert.ok(content.includes(canary));assert.equal(await page.locator('.wf-run-page img[src=x],.wf-run-page script').count(),0);assert.equal(await page.evaluate(()=>window.executionXss),undefined);assert.deepEqual(run.nodes.summary.output.data.summary,{count:3,total:'30.75'});const download=page.waitForEvent('download');await page.getByRole('link',{name:'report.txt',exact:true}).click();const file=await download;let bytes='';for await(const chunk of await file.createReadStream())bytes+=chunk.toString();assert.equal(bytes,'3 orders • 30.75\n');const crypto=await import('node:crypto');assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),crypto.createHash('sha256').update('3 orders • 30.75\n').digest('hex'));const link=await page.getByRole('link',{name:'report.txt',exact:true}).getAttribute('href');const fresh=await browser.newContext();try{assert.equal((await fresh.request.get(origin+link)).status(),401);}finally{await fresh.close();}await page.reload();await page.locator('.wf-run-summary').getByText('Succeeded',{exact:true}).waitFor();await page.goto(origin+'/workflow-runs/'+failed.id);assert.ok((await page.locator('.wf-node-detail[open]').textContent()).includes('prior-failure-only'));
 """)
    assert count(marker)==['invoked'] and count(js_marker)==['invoked']
    assert len(durable_runs(tmp_path))==2


def test_browser_failure_schema_and_timeout_block_javascript_after_reload(engine_url,tmp_path):
    js_marker=tmp_path/'blocked-js.txt'
    browser(engine_url,HELPERS+'const marker='+json.dumps(str(js_marker))+';'+r"""
 for(const variant of ['exception','schema','timeout']){const {id,...template}=(await request('/api/workflow-templates'))[0],p=template.nodes.find(n=>n.id==='summary');p.source=variant==='exception'?'def main(inputs): raise RuntimeError("precise-exception")':variant==='schema'?'def main(inputs): return {"summary":{"count":"wrong","total":"0.00"}}':'import time\ndef main(inputs): time.sleep(10); return {}';if(variant==='timeout')p.config.timeout=1;template.nodes.find(n=>n.id==='report').source='require("fs").appendFileSync('+JSON.stringify(marker)+',"executed");'+template.nodes.find(n=>n.id==='report').source;const w=await seed(template);await open(w);const run=await testRun(w);assert.equal(run.nodes.summary.status,variant==='timeout'?'timed_out':'failed');assert.equal(run.status,variant==='timeout'?'timed_out':'failed');assert.ok(['skipped','not_run'].includes(run.nodes.report.status));assert.equal(run.nodes.report.attempts.length,0);await page.goto(origin+'/workflow-runs/'+run.id);await page.reload();await page.locator('.wf-run-summary').getByText(variant==='timeout'?'Timed out':'Failed',{exact:true}).waitFor();const sourceCard=page.locator('.wf-node-detail').filter({has:page.locator('summary strong').filter({hasText:'Order summary'})});if(await sourceCard.getAttribute('open')===null)await sourceCard.locator('summary').first().click();assert.equal(await sourceCard.locator('.wf-detail-grid').isVisible(),true);const body=await page.locator('body').textContent();assert.ok(body.includes(variant==='exception'?'precise-exception':variant==='schema'?'count':'timed_out'));assert.ok(body.includes('Report file'));}
 """)
    assert count(js_marker)==[]
    assert len(durable_runs(tmp_path))==3


def test_browser_cancel_active_and_queued_preserves_prior_effects(engine_url,tmp_path):
    marker=tmp_path/'cancel-effect.txt';down=tmp_path/'cancel-downstream.txt'
    source=counted_source(marker,"{}").replace('    return','    import time\n    time.sleep(60)\n    return')
    browser(engine_url,HELPERS+'const source='+json.dumps(source)+';const marker='+json.dumps(str(marker))+';const down='+json.dumps(str(down))+';'+r"""
 const w=await seed({nodes:[node('p',{source}),node('down',{source:'from pathlib import Path\ndef main(inputs):\n    Path('+JSON.stringify(down)+').write_text("executed")\n    return {}'})],edges:[{source:'p',target:'down'}]});const admitted=await request('/api/workflows/'+w.id+'/run','POST',{test:true,idempotency_key:'active-cancel'});const fs=await import('node:fs');const deadline=Date.now()+60000;while(!fs.existsSync(marker)&&Date.now()<deadline)await page.waitForTimeout(100);assert.ok(fs.existsSync(marker));await page.goto(origin+'/workflow-runs/'+admitted.id);const pending=page.waitForResponse(r=>r.url().endsWith('/cancel'));await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await(await pending).json()).status,'cancelling');const terminal=await waitRun(admitted);assert.equal(terminal.status,'cancelled');assert.ok(fs.existsSync(marker));assert.equal(terminal.nodes.down.attempts.length,0);await page.reload();await page.locator('.wf-run-summary').getByText('Cancelled',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).count(),0);
 const queued=await seed({nodes:[node('q',{source})],edges:[]});const run=await request('/api/workflows/'+queued.id+'/run','POST',{test:true,idempotency_key:'queued-cancel'});assert.equal(run.status,'queued');await page.goto(origin+'/workflow-runs/'+run.id);const cancel=page.waitForResponse(r=>r.url().endsWith('/cancel'));await page.getByRole('button',{name:'Cancel',exact:true}).click();const ack=await(await cancel).json();assert.equal(ack.status,'cancelled');const stopped=await waitRun(run);assert.equal(stopped.status,'cancelled');assert.equal(stopped.nodes.q.attempts.length,0);await page.reload();await page.locator('.wf-run-summary').getByText('Cancelled',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).count(),0);
 """)
    assert count(marker)==['invoked'] and not down.exists()


def test_browser_operator_runs_published_but_cannot_author(engine_url):
    browser(engine_url,HELPERS+r"""
 const {id,...template}=(await request('/api/workflow-templates'))[0];const w=await seed(template);await request('/api/workflows/'+w.id+'/publish','POST',{});await request('/api/admin/users','POST',{username:'execution-operator',password:'synthetic-operator-only',role:'operator'});await request('/api/logout','POST',{});await page.goto(origin);await page.locator('[name=username]').fill('execution-operator');await page.locator('[name=password]').fill('synthetic-operator-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Open editor',exact:true}).waitFor();await page.goto(origin+'/workflows/'+w.id);for(const label of ['Save draft','Publish','Test workflow'])assert.equal(await page.getByRole('button',{name:label,exact:true}).count(),0);await page.locator('article[data-node-id="orders"]').click();assert.equal(await page.getByLabel('Source code',{exact:true}).isDisabled(),true);const denied=await page.evaluate(async id=>{const boot=await(await fetch('/api/bootstrap')).json();const result=[];for(const path of ['/api/workflows/'+id+'/publish','/api/connections','/api/runtime-profiles']){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':boot.csrf},body:'{}'});result.push(r.status);}return result;},w.id);assert.deepEqual(denied,[403,403,403]);const pending=page.waitForResponse(r=>r.url().endsWith('/run'));await page.getByRole('button',{name:'Run published',exact:true}).first().click();assert.equal((await waitRun(await(await pending).json())).status,'succeeded');
 """)


def test_browser_template_instances_are_independent_and_export_omits_connection(engine_url,tmp_path):
    browser(engine_url,HELPERS+r"""
 const template=(await request('/api/workflow-templates'))[0],created=[];for(let i=0;i<2;i++){await page.goto(origin+'/templates');const pending=page.waitForResponse(r=>r.url().endsWith('/api/workflows')&&r.request().method()==='POST');await page.getByRole('button',{name:'Open visual editor',exact:true}).click();created.push(await(await pending).json());}assert.notEqual(created[0].id,created[1].id);const original=structuredClone(created[1]);await open(created[0]);await sourceCode('summary','def main(inputs): return {"summary":{"count":99,"total":"0.00"}}');await save(created[0]);assert.deepEqual((await request('/api/workflows/'+created[1].id)).nodes,original.nodes);assert.deepEqual((await request('/api/workflow-templates'))[0],template);await open(created[1]);const run=await testRun(created[1]);assert.equal(run.status,'succeeded');assert.deepEqual(run.nodes.summary.output.data.summary,{count:3,total:'30.75'});const connection=await request('/api/connections','POST',{name:'Explicit replacement',dialect:'sqlite',config:{synthetic:true}});await open(created[1]);await selectNode('orders');await page.getByLabel('Connection',{exact:true}).selectOption(connection.id);await save(created[1]);assert.equal((await request('/api/workflows/'+created[0].id)).nodes.find(n=>n.id==='orders').config.connection_id,template.nodes.find(n=>n.id==='orders').config.connection_id);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByText('Advanced settings',{exact:true}).click();const exported=page.waitForResponse(r=>r.url().endsWith('/export'));const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export portable template',exact:true}).click();const response=await exported;assert.equal(response.status(),200,await response.text());let text='';for await(const part of await(await download).createReadStream())text+=part.toString();assert.equal(text.includes(connection.id),false);assert.equal(text.includes(run.id),false);assert.equal(text.includes('encrypted_config'),false);
 """)
    assert len(durable_runs(tmp_path))==1
