"""Real browser schedule forms, explicit preview clocks and isolated scheduler ticks."""
import json
import sys

from test_acceptance_browser import browser, engine_url, isolated_url, pytestmark
from test_acceptance_browser_mapping import durable_runs


HELPERS=r"""
const triggers=async w=>{await open(w);await page.getByRole('button',{name:'Triggers',exact:true}).click();};
let previewAfter='2026-09-20T00:00:00Z';
await page.route('**/api/workflows/*/preview',async route=>{const body=route.request().postDataJSON();await route.continue({postData:JSON.stringify({...body,after:previewAfter})});});
const preview=async()=>{const pending=page.waitForResponse(r=>r.url().endsWith('/preview'));await page.getByRole('button',{name:'Preview next five',exact:true}).click();const response=await pending;return {status:response.status(),value:await response.json()};};
const saveSchedule=async w=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/workflows/'+w.id)&&r.request().method()==='PUT');await page.getByRole('button',{name:'Save draft',exact:true}).last().click();return pending;};
const raw=async(path,method,body)=>page.evaluate(async({path,method,body})=>{const boot=await(await fetch('/api/bootstrap')).json();const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':boot.csrf},body:JSON.stringify(body)});return {status:r.status,value:await r.json()};},{path,method,body});
const untilDone=async id=>{let result;const until=Date.now()+90000;do{result=await request('/api/workflow-runs/'+id);if(!['queued','running','cancelling'].includes(result.status))break;await page.waitForTimeout(150);}while(Date.now()<until);return result;};
"""


def clock_driver(tmp_path):
    code="import json,sys;from datetime import datetime;from taskconsole.store import Store;from taskconsole.workflows import WorkflowService;store=Store(sys.argv[1],'sqlite:///'+sys.argv[1]+'/browser.sqlite');service=WorkflowService(store);print(json.dumps([r['id'] for r in service.tick(datetime.fromisoformat(sys.argv[2].replace('Z','+00:00')))]))"
    return "const {execFileSync}=await import('node:child_process');const tick=at=>JSON.parse(execFileSync("+json.dumps(sys.executable)+",['-c',"+json.dumps(code)+","+json.dumps(str(tmp_path))+",at],{encoding:'utf8'}));"


def test_browser_weekday_protocol_and_chicago_locale_reload_are_exact(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const w=await seed({nodes:[node('a')],edges:[]});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('weekly');await page.getByLabel('Wed',{exact:true}).check();await page.getByLabel('Time',{exact:true}).fill('07:00');let result=await preview();assert.deepEqual(result.value.next_runs.slice(0,3),['2026-09-21T07:00:00+00:00','2026-09-23T07:00:00+00:00','2026-09-28T07:00:00+00:00']);assert.equal((await saveSchedule(w)).status(),200);let saved=await request('/api/workflows/'+w.id);assert.deepEqual(saved.schedule.weekdays,[0,2]);
 await page.getByLabel('Schedule',{exact:true}).selectOption('daily');await page.getByLabel('Time',{exact:true}).fill('07:00');await page.getByLabel('Timezone',{exact:true}).fill('America/Chicago');await page.getByLabel('Schedule enabled',{exact:true}).check();assert.equal((await saveSchedule(w)).status(),200);saved=await request('/api/workflows/'+w.id);const before=await preview();assert.equal(before.value.next_runs[0],'2026-09-20T12:00:00+00:00');assert.ok((await page.locator('.wf-preview').textContent()).includes('7:00'));await page.locator('[data-locale="zh-CN"]').click();await page.reload();await page.getByRole('button',{name:'触发器',exact:true}).click();assert.equal(await page.getByLabel('时间',{exact:true}).inputValue(),'07:00');assert.equal(await page.getByLabel('时区',{exact:true}).inputValue(),'America/Chicago');const chineseResponse=page.waitForResponse(r=>r.url().endsWith('/preview'));await page.getByRole('button',{name:'预览接下来五次',exact:true}).click();assert.deepEqual((await(await chineseResponse).json()).next_runs,before.value.next_runs);await page.locator('[data-locale="en"]').click();assert.deepEqual((await preview()).value.next_runs,before.value.next_runs);const after=await request('/api/workflows/'+w.id);assert.deepEqual(after.schedule,saved.schedule);assert.equal(after.timezone,saved.timezone);assert.equal(after.enabled,true);assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)


def test_browser_expired_once_is_not_labelled_manual_and_never_replays(isolated_url,tmp_path):
    browser(isolated_url,HELPERS+clock_driver(tmp_path)+r"""
 const w=await seed({nodes:[node('a')],edges:[]});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('once');await page.getByLabel('Date',{exact:true}).fill('2020-01-01');await page.getByLabel('Time',{exact:true}).fill('07:00');await page.getByLabel('Schedule enabled',{exact:true}).check();const result=await preview();assert.equal(result.status,200);assert.deepEqual(result.value.next_runs,[]);assert.ok((await page.locator('.wf-preview').textContent()).includes('This one-time schedule has expired'));assert.equal((await page.locator('.wf-preview').textContent()).includes('Manual only'),false);assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick('2026-09-20T00:00:00Z'),[]);assert.deepEqual(tick('2026-09-21T07:00:00Z'),[]);assert.deepEqual(await request('/api/workflow-runs'),[]);await triggers(w);assert.equal(await page.getByLabel('Date',{exact:true}).inputValue(),'2020-01-01');assert.deepEqual((await preview()).value.next_runs,[]);
 """)


def test_browser_invalid_schedule_preview_clears_old_occurrences_without_server_mutation(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const w=await seed({nodes:[node('a')],edges:[],schedule:{kind:'daily',time:'07:30'}});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);const baseline=await request('/api/workflows/'+w.id);assert.equal((await preview()).value.next_runs.length,5);await page.getByLabel('Timezone',{exact:true}).fill('Not/A_Zone');const invalid=await preview();assert.equal(invalid.status,400);assert.ok(invalid.value.detail.message.includes('timezone'));assert.equal(await page.locator('.wf-preview > div').count(),0);assert.ok((await page.locator('.wf-preview [role="alert"]').textContent()).includes('timezone'));assert.equal((await saveSchedule(w)).status(),400);assert.deepEqual((await request('/api/workflows/'+w.id)).schedule,baseline.schedule);assert.equal((await request('/api/workflows/'+w.id)).timezone,baseline.timezone);assert.equal(await page.getByLabel('Time',{exact:true}).inputValue(),'07:30');assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)


def test_browser_all_schedule_forms_roundtrip_without_stale_kind_fields(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const w=await seed({nodes:[node('a')],edges:[]});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);previewAfter='2026-09-20T00:07:00Z';
 const variants=[['manual',{},[]],['interval',{every:15,unit:'minutes',anchor:'2026-09-20T00:00:00Z'},['2026-09-20T00:15:00+00:00','2026-09-20T00:30:00+00:00']],['interval',{every:2,unit:'hours',anchor:'2026-09-20T00:00:00Z'},['2026-09-20T02:00:00+00:00','2026-09-20T04:00:00+00:00']],['daily',{time:'07:30'},['2026-09-20T07:30:00+00:00']],['weekly',{time:'07:30',weekdays:[0,3]},['2026-09-21T07:30:00+00:00','2026-09-24T07:30:00+00:00']],['monthly',{time:'07:30',day:15},['2026-10-15T07:30:00+00:00']],['monthly',{time:'07:30',day:'last'},['2026-09-30T07:30:00+00:00']],['once',{time:'07:30',date:'2026-09-21'},['2026-09-21T07:30:00+00:00']]];
 for(const [kind,values,expected] of variants){await page.getByLabel('Schedule',{exact:true}).selectOption(kind);if(values.every){await page.getByLabel('Every',{exact:true}).fill(String(values.every));await page.getByLabel('Time',{exact:true}).selectOption(values.unit);await page.getByLabel('Starting anchor',{exact:true}).fill(values.anchor);}else if(values.time)await page.getByLabel('Time',{exact:true}).fill(values.time);if(values.weekdays)await page.getByLabel('Thu',{exact:true}).check();if(values.day)await page.getByLabel('Day of month',{exact:true}).selectOption(String(values.day));if(values.date)await page.getByLabel('Date',{exact:true}).fill(values.date);let value=await preview();assert.equal(value.status,200);assert.deepEqual(value.value.next_runs.slice(0,expected.length),expected);if(kind==='manual'||kind==='once')assert.equal(value.value.next_runs.length,expected.length);assert.equal((await saveSchedule(w)).status(),200);const saved=await request('/api/workflows/'+w.id);const canonical={kind,...values};if(canonical.anchor)canonical.anchor=canonical.anchor.replace('Z','+00:00');assert.deepEqual(saved.schedule,canonical);assert.equal(saved.enabled,false);await triggers(w);assert.equal(await page.getByLabel('Schedule',{exact:true}).inputValue(),kind);assert.deepEqual((await preview()).value.next_runs,value.value.next_runs);assert.equal(await page.locator('input[name="cron"]').count(),0);}
 await page.getByLabel('Schedule',{exact:true}).selectOption('daily');await page.getByLabel('Multiple times (optional)',{exact:true}).fill('18:30, 07:00, 07:00');assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual((await request('/api/workflows/'+w.id)).schedule.times,['07:00','18:30']);assert.deepEqual((await preview()).value.next_runs.slice(0,3),['2026-09-20T07:00:00+00:00','2026-09-20T18:30:00+00:00','2026-09-21T07:00:00+00:00']);assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)


def test_browser_month_bounds_and_dst_previews_match_controlled_dispatch(isolated_url,tmp_path):
    browser(isolated_url,HELPERS+clock_driver(tmp_path)+r"""
 const one=async at=>{const ids=tick(at);assert.equal(ids.length,1);assert.equal((await request('/api/workflow-runs/'+ids[0])).scheduled_at,at.replace('Z','+00:00'));await request('/api/workflow-runs/'+ids[0]+'/cancel','POST',{});};const w=await seed({nodes:[node('a')],edges:[]});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('monthly');await page.getByLabel('Time',{exact:true}).fill('07:00');await page.getByLabel('Day of month',{exact:true}).selectOption('31');previewAfter='2026-04-01T00:00:00Z';assert.equal((await preview()).value.next_runs[0],'2026-05-31T07:00:00+00:00');await page.getByLabel('Schedule enabled',{exact:true}).check();assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick('2026-04-01T00:00:00Z'),[]);assert.deepEqual(tick('2026-04-30T07:00:00Z'),[]);await one('2026-05-31T07:00:00Z');await page.getByLabel('Day of month',{exact:true}).selectOption('last');previewAfter='2028-02-01T00:00:00Z';assert.equal((await preview()).value.next_runs[0],'2028-02-29T07:00:00+00:00');assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick('2028-02-01T00:00:00Z'),[]);await one('2028-02-29T07:00:00Z');previewAfter='2029-02-01T00:00:00Z';assert.equal((await preview()).value.next_runs[0],'2029-02-28T07:00:00+00:00');assert.deepEqual(tick('2029-02-01T00:00:00Z'),[]);await one('2029-02-28T07:00:00Z');await page.getByLabel('Starts on (optional)',{exact:true}).fill('2029-03-01T00:00:00Z');await page.getByLabel('Ends on (optional)',{exact:true}).fill('2029-04-30T07:00:00Z');const bounded=await preview();assert.deepEqual(bounded.value.next_runs,['2029-03-31T07:00:00+00:00','2029-04-30T07:00:00+00:00']);assert.equal(await page.locator('.wf-preview > div').count(),2);assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick('2029-03-01T00:00:00Z'),[]);await one('2029-03-31T07:00:00Z');await one('2029-04-30T07:00:00Z');assert.deepEqual(tick('2029-05-31T07:00:00Z'),[]);
 for(const [after,time,expected] of [['2027-03-14T00:00:00Z','02:30',['2027-03-15T06:30:00+00:00','2027-03-16T06:30:00+00:00']],['2027-11-07T00:00:00Z','01:30',['2027-11-07T05:30:00+00:00','2027-11-08T06:30:00+00:00']]]){await page.getByLabel('Schedule',{exact:true}).selectOption('daily');await page.getByLabel('Timezone',{exact:true}).fill('America/New_York');await page.getByLabel('Time',{exact:true}).fill(time);previewAfter=after;const before=await preview();assert.deepEqual(before.value.next_runs.slice(0,2),expected);assert.ok((await page.locator('.wf-preview').textContent()).includes('America/New_York'));assert.ok((await page.locator('.wf-preview time').first().textContent()).includes('GMT-4'));if(time==='01:30')assert.ok((await page.locator('.wf-preview time').nth(1).textContent()).includes('GMT-5'));await page.locator('[data-locale="zh-CN"]').click();const response=page.waitForResponse(r=>r.url().endsWith('/preview'));await page.getByRole('button',{name:'预览接下来五次',exact:true}).click();assert.deepEqual((await(await response).json()).next_runs,before.value.next_runs);await page.locator('[data-locale="en"]').click();await page.getByLabel('Schedule enabled',{exact:true}).check();assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick(after),[]);const admitted=tick(expected[0]);assert.equal(admitted.length,1);assert.deepEqual(tick(expected[0]),[]);if(time==='01:30')assert.deepEqual(tick('2027-11-07T06:30:00Z'),[]);const run=await request('/api/workflow-runs/'+admitted[0]);assert.equal(run.scheduled_at,expected[0]);await request('/api/workflow-runs/'+run.id+'/cancel','POST',{});}
 """)


def test_browser_local_dst_boundaries_persist_first_fold_and_reject_gap(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const w=await seed({nodes:[node('a')],edges:[]});await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('daily');await page.getByLabel('Time',{exact:true}).fill('01:30');await page.getByLabel('Timezone',{exact:true}).fill('America/New_York');await page.getByLabel('Starts on (optional)',{exact:true}).fill('2027-11-07T01:30:00');await page.getByLabel('Ends on (optional)',{exact:true}).fill('2027-11-08T01:30:00');previewAfter='2027-11-06T00:00:00Z';assert.deepEqual((await preview()).value.next_runs,['2027-11-07T05:30:00+00:00','2027-11-08T06:30:00+00:00']);assert.equal((await saveSchedule(w)).status(),200);const saved=await request('/api/workflows/'+w.id);assert.equal(saved.schedule.start,'2027-11-07T05:30:00+00:00');assert.equal(saved.schedule.end,'2027-11-08T06:30:00+00:00');await page.getByLabel('Starts on (optional)',{exact:true}).fill('2027-03-14T02:30:00');const gap=await preview();assert.equal(gap.status,400);assert.ok(gap.value.detail.message.includes('nonexistent local time'));assert.equal((await saveSchedule(w)).status(),400);assert.deepEqual((await request('/api/workflows/'+w.id)).schedule,saved.schedule);assert.equal(await page.getByLabel('Timezone',{exact:true}).inputValue(),'America/New_York');assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)


def test_browser_weekday_form_summary_admits_published_template_with_real_n8n(engine_url,tmp_path):
    browser(engine_url,HELPERS+clock_driver(tmp_path)+r"""
 const {id,...template}=(await request('/api/workflow-templates'))[0];const w=await seed(template);const published=await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('weekdays');await page.getByLabel('Time',{exact:true}).fill('07:30');await page.getByLabel('Timezone',{exact:true}).fill('Asia/Shanghai');await page.getByLabel('Schedule enabled',{exact:true}).check();const value=await preview();assert.equal(value.value.next_runs.length,5);assert.equal(value.value.next_runs[0],'2026-09-20T23:30:00+00:00');assert.equal(await page.locator('.wf-preview time').count(),5);assert.equal(await page.locator('input[name="cron"]').count(),0);const summary=await page.locator('.wf-schedule-summary').textContent();assert.ok(summary.includes('Monday–Friday'));assert.ok(summary.includes('07:30'));assert.ok(summary.includes('Asia/Shanghai'));assert.equal((await saveSchedule(w)).status(),200);await triggers(w);assert.equal(await page.getByLabel('Schedule enabled',{exact:true}).isChecked(),true);assert.equal(await page.getByLabel('Time',{exact:true}).inputValue(),'07:30');assert.equal(await page.getByLabel('Timezone',{exact:true}).inputValue(),'Asia/Shanghai');assert.deepEqual(tick('2026-09-20T23:29:59Z'),[]);const ids=tick('2026-09-20T23:30:00Z');assert.equal(ids.length,1);const run=await untilDone(ids[0]);assert.equal(run.status,'succeeded',JSON.stringify({error:run.error,nodes:run.nodes}));assert.equal(run.version_id,published.version_id);assert.equal(run.scheduled_at,'2026-09-20T23:30:00+00:00');assert.equal(run.engine,'n8n');assert.deepEqual(run.nodes.summary.output.data.summary,{count:3,total:'30.75'});assert.deepEqual(run.nodes.report.inputs,{summary:{count:3,total:'30.75'}});assert.deepEqual(tick('2026-09-20T23:30:00Z'),[]);await page.goto(origin+'/workflow-runs/'+run.id);await page.locator('.wf-run-summary').getByText('Succeeded',{exact:true}).waitFor();assert.ok((await page.locator('.wf-run-summary').textContent()).includes(published.version_id));
 """)
    assert len(durable_runs(tmp_path))==1


def test_browser_invalid_form_matrix_rejects_enable_and_preserves_saved_state(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const cases=[['timezone',{kind:'daily',time:'07:30'},'Invalid/Zone'],['zero',{kind:'interval',every:0,unit:'minutes',anchor:'2026-09-20T00:00:00Z'},'UTC'],['negative',{kind:'interval',every:-1,unit:'minutes',anchor:'2026-09-20T00:00:00Z'},'UTC'],['fraction',{kind:'interval',every:1.5,unit:'minutes',anchor:'2026-09-20T00:00:00Z'},'UTC'],['boolean',{kind:'interval',every:true,unit:'minutes',anchor:'2026-09-20T00:00:00Z'},'UTC'],['clock',{kind:'daily',time:'25:00'},'UTC'],['weekdays',{kind:'weekly',time:'07:30',weekdays:[]},'UTC'],['monthday',{kind:'monthly',time:'07:30',day:32},'UTC'],['bounds',{kind:'daily',time:'07:30',start:'2027-01-02T00:00:00Z',end:'2027-01-01T00:00:00Z'},'UTC'],['once',{kind:'once',time:'07:30',date:''},'UTC']];
 for(const [name,schedule,timezone] of cases){const w=await seed({name:'Preserve '+name,nodes:[node('a')],edges:[]});const denied=await raw('/api/workflows/'+w.id,'PUT',{...w,schedule:{kind:'daily',time:'07:30'},enabled:true});assert.equal(denied.status,422);await triggers(w);assert.equal(await page.getByLabel('Schedule enabled',{exact:true}).isDisabled(),true);await request('/api/workflows/'+w.id+'/publish','POST',{});const rejected=await raw('/api/workflows/'+w.id+'/preview','POST',{schedule,timezone,after:previewAfter});assert.ok([400,422].includes(rejected.status));assert.ok(rejected.value.detail.message.length>0);
 // Boolean, out-of-range month-day and invalid clock cannot be typed into native
 // controls; load an incomplete API-authored draft to verify the UI rejects them.
 if(['boolean','clock','monthday'].includes(name)){const current=await request('/api/workflows/'+w.id);const draft=await raw('/api/workflows/'+w.id,'PUT',{...current,schedule,timezone,enabled:false});assert.equal(draft.status,200);assert.ok(draft.value.validation_errors.length);}
 await triggers(w);if(!['boolean','clock','monthday'].includes(name)){await page.getByLabel('Schedule',{exact:true}).selectOption(schedule.kind);if(schedule.kind==='interval'){await page.getByLabel('Every',{exact:true}).fill(String(schedule.every));await page.getByLabel('Starting anchor',{exact:true}).fill(schedule.anchor);}else{await page.getByLabel('Time',{exact:true}).fill(schedule.time);if(name==='weekdays')await page.getByLabel('Mon',{exact:true}).uncheck();if(name==='once')await page.getByLabel('Date',{exact:true}).fill('');if(name==='bounds'){await page.getByLabel('Starts on (optional)',{exact:true}).fill(schedule.start);await page.getByLabel('Ends on (optional)',{exact:true}).fill(schedule.end);}}await page.getByLabel('Timezone',{exact:true}).fill(timezone);}if(name==='boolean')assert.equal(await page.getByLabel('Every',{exact:true}).getAttribute('type'),'number');if(name==='monthday')assert.equal(await page.getByLabel('Day of month',{exact:true}).locator('option[value="32"]').count(),0);
 const before=await request('/api/workflows/'+w.id);const result=await preview();assert.ok([400,422].includes(result.status));assert.ok((await page.locator('.wf-preview [role="alert"]').textContent()).length>0);assert.equal(await page.locator('.wf-preview > div').count(),0);await page.getByLabel('Schedule enabled',{exact:true}).check();if(await page.locator('.wf-form :invalid').count()){await page.getByRole('button',{name:'Save draft',exact:true}).last().click();assert.ok(await page.locator('.wf-form :invalid').first().evaluate(el=>el.validationMessage.length>0));}else{const response=await saveSchedule(w);assert.ok([400,422].includes(response.status()));}const independent=await raw('/api/workflows/'+w.id,'PUT',{...before,schedule,timezone,enabled:true});assert.ok([400,422].includes(independent.status));const after=await request('/api/workflows/'+w.id);assert.deepEqual(after.schedule,before.schedule);assert.equal(after.timezone,before.timezone);assert.equal(after.enabled,false);assert.equal(after.name,'Preserve '+name);await page.getByLabel('Schedule enabled',{exact:true}).uncheck();await page.getByLabel('Timezone',{exact:true}).fill('UTC');await page.getByLabel('Schedule',{exact:true}).selectOption('manual');assert.equal((await saveSchedule(w)).status(),200);assert.equal((await request('/api/workflows/'+w.id)).name,'Preserve '+name);}
 assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)


def test_browser_pause_edit_publish_and_reenable_keeps_admitted_version(engine_url,tmp_path):
    from test_acceptance_browser_mapping import counted_source,count
    counter=tmp_path/'schedule-versions-counter.txt'
    browser(engine_url,HELPERS+clock_driver(tmp_path)+'const sources='+json.dumps([counted_source(counter,"{'version':1}"),counted_source(counter,"{'version':2}")])+';'+r"""
 const w=await seed({nodes:[node('a',{source:sources[0]})],edges:[]});const v1=await request('/api/workflows/'+w.id+'/publish','POST',{});await triggers(w);await page.getByLabel('Schedule',{exact:true}).selectOption('daily');await page.getByLabel('Time',{exact:true}).fill('07:00');await page.getByLabel('Schedule enabled',{exact:true}).check();assert.ok((await page.locator('.wf-save-state').textContent()).includes('Unsaved'));assert.equal((await request('/api/workflows/'+w.id)).enabled,false);assert.equal((await saveSchedule(w)).status(),200);assert.deepEqual(tick('2026-09-21T06:59:59Z'),[]);const priorIds=tick('2026-09-21T07:00:00Z');assert.equal(priorIds.length,1);await page.getByLabel('Schedule enabled',{exact:true}).uncheck();assert.equal((await saveSchedule(w)).status(),200);assert.notEqual((await request('/api/workflow-runs/'+priorIds[0])).status,'cancelled');await page.getByRole('button',{name:'Editor',exact:true}).click();await page.locator('article[data-node-id="a"]').click();await page.getByLabel('Source code',{exact:true}).fill(sources[1]);await save(w);assert.equal((await request('/api/workflows/'+w.id)).published_version_id,v1.version_id);assert.deepEqual(tick('2026-09-22T07:00:00Z'),[]);const prior=await untilDone(priorIds[0]);assert.equal(prior.status,'succeeded',prior.error);assert.equal(prior.version_id,v1.version_id);assert.deepEqual(prior.nodes.a.output.data,{version:1});const published=page.waitForResponse(r=>r.url().endsWith('/publish'));await page.getByRole('button',{name:'Publish',exact:true}).click();const v2=await(await published).json();assert.notEqual(v2.version_id,v1.version_id);await page.getByRole('button',{name:'Triggers',exact:true}).click();assert.equal(await page.getByLabel('Schedule enabled',{exact:true}).isChecked(),false);await page.getByLabel('Schedule enabled',{exact:true}).check();assert.equal((await saveSchedule(w)).status(),200);const futureIds=tick('2026-09-23T07:00:00Z');assert.equal(futureIds.length,1);const future=await untilDone(futureIds[0]);assert.equal(future.status,'succeeded',future.error);assert.equal(future.version_id,v2.version_id);assert.deepEqual(future.nodes.a.output.data,{version:2});assert.deepEqual(tick('2026-09-23T07:00:00Z'),[]);const runs=await request('/api/workflow-runs');assert.equal(runs.length,2);assert.deepEqual(runs.map(r=>r.scheduled_at).sort(),['2026-09-21T07:00:00+00:00','2026-09-23T07:00:00+00:00']);
 """)
    records=durable_runs(tmp_path)
    assert len(records)==2 and count(counter)==['invoked']*2
    assert len({r['version_id'] for r in records})==2


def test_browser_delayed_and_out_of_order_previews_cannot_replace_current_form(isolated_url):
    browser(isolated_url,HELPERS+r"""
 const w=await seed({nodes:[node('a')],edges:[],schedule:{kind:'daily',time:'07:30'}});await triggers(w);await page.unroute('**/api/workflows/*/preview');let release,ready;let gate=new Promise(r=>release=r),observed=new Promise(r=>ready=r);let sequence=0;
 await page.route('**/api/workflows/*/preview',async route=>{const n=++sequence,body=route.request().postDataJSON();const response=await route.fetch({postData:JSON.stringify({...body,after:'2026-09-20T00:00:00Z'})});if(n===1){ready();await gate;}await route.fulfill({response});});await page.getByRole('button',{name:'Preview next five',exact:true}).click();await observed;await page.getByLabel('Timezone',{exact:true}).fill('Asia/Shanghai');await page.getByLabel('Time',{exact:true}).fill('08:00');const late=page.waitForResponse(r=>r.url().endsWith('/preview'));release();await late;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await page.locator('.wf-preview time').count(),0);assert.ok((await page.locator('.wf-preview').textContent()).includes('Choose a schedule'));
 await page.unroute('**/api/workflows/*/preview');sequence=0;gate=new Promise(r=>release=r);observed=new Promise(r=>ready=r);await page.route('**/api/workflows/*/preview',async route=>{const n=++sequence,body=route.request().postDataJSON();const response=await route.fetch({postData:JSON.stringify({...body,after:n===1?'2026-09-20T00:00:00Z':'2026-09-21T00:00:00Z'})});if(n===1){ready();await gate;}await route.fulfill({response});});await page.getByRole('button',{name:'Preview next five',exact:true}).click();await observed;const newest=await preview();assert.equal(newest.value.next_runs[0],'2026-09-22T00:00:00+00:00');await page.locator('.wf-preview time').first().waitFor();assert.equal(await page.locator('.wf-preview time').first().getAttribute('datetime'),newest.value.next_runs[0]);const older=page.waitForResponse(r=>r.url().endsWith('/preview'));release();await older;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await page.locator('.wf-preview time').first().getAttribute('datetime'),newest.value.next_runs[0]);assert.equal(await page.getByLabel('Timezone',{exact:true}).inputValue(),'Asia/Shanghai');assert.equal(await page.getByLabel('Time',{exact:true}).inputValue(),'08:00');assert.deepEqual(await request('/api/workflow-runs'),[]);
 """)
